// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import AvatarController from "./avatar_controller"
application.register("avatar", AvatarController)

import DrawerController from "./drawer_controller"
application.register("drawer", DrawerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)

import VisibilityController from "./visibility_controller"
application.register("visibility", VisibilityController)


import EditableFieldController from "./editable_field_controller"
application.register("editable-field", EditableFieldController)

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import UserSearchController from "./user_search_controller"
application.register("user-search", UserSearchController)

import MultiSelectController from "./multi_select_controller"
application.register("multi-select", MultiSelectController)

import RecurrenceToggleController from "./recurrence_toggle_controller"
application.register("recurrence-toggle", RecurrenceToggleController)

import QuestionnaireController from "./questionnaire_controller"
application.register("questionnaire", QuestionnaireController)

import QuestionnaireSubmitController from "./questionnaire_submit_controller"
application.register("questionnaire-submit", QuestionnaireSubmitController)