// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import AttendanceController from "./attendance_controller"
application.register("attendance", AttendanceController)

import AvatarController from "./avatar_controller"
application.register("avatar", AvatarController)

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import ColorPickerController from "./color_picker_controller"
application.register("color-picker", ColorPickerController)

import DatesController from "./dates_controller"
application.register("dates", DatesController)

import DrawerController from "./drawer_controller"
application.register("drawer", DrawerController)

import EditableFieldController from "./editable_field_controller"
application.register("editable-field", EditableFieldController)

import ExerciseSearchController from "./exercise_search_controller"
application.register("exercise-search", ExerciseSearchController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImagePreviewController from "./image_preview_controller"
application.register("image-preview", ImagePreviewController)

import KpiFormController from "./kpi_form_controller"
application.register("kpi-form", KpiFormController)

import KpiSearchInputController from "./kpi_search_input_controller"
application.register("kpi-search-input", KpiSearchInputController)

import KpiTableController from "./kpi_table_controller"
application.register("kpi-table", KpiTableController)

import LevelController from "./level_controller"
application.register("level", LevelController)

import MobileMenuController from "./mobile_menu_controller"
application.register("mobile-menu", MobileMenuController)

import MultiSelectController from "./multi_select_controller"
application.register("multi-select", MultiSelectController)

import QuestionnaireController from "./questionnaire_controller"
application.register("questionnaire", QuestionnaireController)

import QuestionnaireSubmitController from "./questionnaire_submit_controller"
application.register("questionnaire-submit", QuestionnaireSubmitController)

import RecurrenceToggleController from "./recurrence_toggle_controller"
application.register("recurrence-toggle", RecurrenceToggleController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import SignupValidationController from "./signup_validation_controller"
application.register("signup-validation", SignupValidationController)

import TestController from "./test_controller"
application.register("test", TestController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)

import UserSearchController from "./user_search_controller"
application.register("user-search", UserSearchController)

import UserTableController from "./user_table_controller"
application.register("user-table", UserTableController)

import VisibilityController from "./visibility_controller"
application.register("visibility", VisibilityController)

import kpi_search_input_controller from "./kpi_search_input_controller"
application.register("kpi-search-input", kpi_search_input_controller)
