plugins:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

Performance:
  Enabled: true

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'config/routes.rb'
    - 'config/initializers/*'
    - 'config/environments/*'

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - 'db/migrate/*'

Metrics/AbcSize:
  Enabled: true
  Exclude:
    - 'db/migrate/*'