services:
  production-app:
    container_name: portal-production-app
    build: .
    command: >
      bash -c "rm -f /usr/src/app/tmp/pids/server.pid &&
               RAILS_ENV=${RAILS_ENV} bundle exec rails db:migrate &&
               RAILS_ENV=${RAILS_ENV} bundle exec rails db:seed &&
               RAILS_ENV=${RAILS_ENV} bundle exec rails assets:precompile &&
               RAILS_ENV=${RAILS_ENV} bundle exec rails server -b 0.0.0.0 -p 3000"
    volumes:
      - portal-production-app-volume:/usr/src/app
    ports:
      - "3000:3000"
    env_file: .env.production

volumes:
  portal-production-app-volume:
