services:
  staging-app:
    container_name: portal-staging-app
    build: .
    command: >
      bash -c "rm -f /usr/src/app/tmp/pids/server.pid &&
               RAILS_ENV=${RAILS_ENV} bundle exec rails db:migrate &&
               RAILS_ENV=${RAILS_ENV} bundle exec rails db:seed &&
               RAILS_ENV=${RAILS_ENV} bundle exec rails assets:precompile &&
               RAILS_ENV=${RAILS_ENV} bundle exec rails server -b 0.0.0.0 -p 3001"
    volumes:
      - portal-staging-app-volume:/usr/src/app
    ports:
      - "3001:3001"
    env_file: .env.staging

volumes:
  portal-staging-app-volume:
