default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  encoding: <%= ENV['DB_ENCODE'] %>
  prepared_statements: false
  host: <%= ENV['DB_HOST'] %>

test:
  <<: *default
  database: portal_test

production:
  <<: *default
  database: <%= ENV['SQL_DB_NAME'] %>
  username: <%= ENV['SQL_DB_USER'] %>
  password: <%= ENV['SQL_DB_PASSWORD'] %>
  encoding: <%= ENV['DB_ENCODE'] %>
  prepared_statements: false
  host: <%= ENV['SQL_HOST'] %>
