name: CI Pipeline (Tests Only)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  RAILS_ENV: test
  DB_NAME: rails_app_test
  DB_USER: postgres
  DB_PASSWORD: postgres
  DATABASE_URL: postgres://postgres:postgres@postgres:5432/rails_app_test
  REDIS_URL: redis://redis:6379/0

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ env.DB_NAME }}
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2
        bundler-cache: true
        bundler: 2.4.22

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get -yqq install libpq-dev

    - name: Verify database connectivity
      run: |
        echo "Waiting for PostgreSQL..."
        timeout 20s bash -c 'until pg_isready -h postgres -p 5432; do sleep 1; done'
        echo "PostgreSQL ready!"

    - name: Setup test database
      run: |
        bundle exec rails db:create
        bundle exec rails db:schema:load
        bundle exec rails db:migrate

    - name: Run RSpec tests
      run: bundle exec rspec

    - name: Run Rubocop
      run: bundle exec rubocop

    - name: Run Brakeman (security scan)
      run: bundle exec brakeman --no-pager --exit-on-warn